name: Build RSDKv5

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet Packages
        run: nuget restore RSDKv5.sln

      - name: Build Solution
        run: msbuild RSDKv5.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSDKv5-windows-x64
          path: |
            **/Release/*.exe
            **/Release/*.dll
