name: Build RSDKv5

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  GENERAL_FLAGS: "-DCMAKE_BUILD_TYPE=Release"
  GENERAL_WIN_FLAGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
  WIN64_FLAGS: "-DVCPKG_TARGET_TRIPLET=x64-windows-static"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          vcpkg install sdl2:x64-windows-static glew:x64-windows-static

      - name: Build RSDKv5
        run: |
          mkdir build
          cd build
          cmake .. ${{ env.GENERAL_FLAGS }} ${{ env.GENERAL_WIN_FLAGS }} ${{ env.WIN64_FLAGS }}
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RSDKv5-windows-x64
          path: |
            build/Release/*.exe
            build/Release/*.dll
